---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(jsonlite)
library(magrittr)
```
user activity endpoint
http://ikarion.collide.info:5000/user_model/user_actions/<course_id>/<user_id>/<verb>

```{r}
getData <- function(...) {
  
  paste("http://ikarion.collide.info:5000", ..., sep="/") %>%
  #paste("http://descartes.inf.uni-due.de:5000", ..., sep="/") %>%
    URLencode %>%
    #print() %>% 
    fromJSON %>%
    extract2("data")
}

replaceUrlChars <- function(string) {
  string <- gsub("/", "$slash$", string)
  string <- gsub("?", "$qmark$", string, fixed = T)
}

all_data <- data_frame()

getUserActivities <- function(course_id, user_id, verb) {
  data <- getData("user_model/user_actions", course_id, replaceUrlChars(user_id), verb)
  if (length(data) > 0) {
    data <- data %>% subset(select = -object_name)
    all_data <<- rbind(all_data, data)
  }
}



```


getting user list for cvk course
```{r}
#http://ikarion.collide.info:5000/user_model/https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=11

course_id <- "https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=22"
login <- "https://brindlewaye.com/xAPITerms/verbs/loggedin/" %>% replaceUrlChars()
view <- "http://id.tincanapi.com/verb/viewed" %>% replaceUrlChars()

verb <- login

users <- getData("user_model") %>% 
  as_data_frame %>% 
  rename(user_id = value)

for (user in users$user_id) {
  getUserActivities(course_id, user, verb)
}
```

```{r}
login_data <- all_data 

login_data$date <- as.POSIXct(login_data$timestamp, origin="1970-01-01")

# start + end timestamps
task1_start <- 1571652000
task1_end <- 1572822300

task2_start <- 1572865200
task2_end <- 1574031900

task3_start <-  1574074800
task3_end <-    1575241500

task4_start <-  1575284400
task4_end <-    1576451100

login_data$task <- NA

login_data$task[login_data$timestamp>task1_start & login_data$timestamp<task1_end] <- "task1"
login_data$task[login_data$timestamp>task2_start & login_data$timestamp<task2_end] <- "task2"
login_data$task[login_data$timestamp>task3_start & login_data$timestamp<task3_end] <- "task3"
login_data$task[login_data$timestamp>task4_start & login_data$timestamp<task4_end] <- "task4"
#login_data$task[login_data$timestamp>task5_start & login_data$timestamp<task5_end] <- "task5"
#login_data$task[login_data$timestamp>task6_start & login_data$timestamp<task6_end] <- "task6"

```

```{r}

groups_and_users_t1 <- read.csv2("/home/doberstein/Dropbox/D/uni/IKARion/CVK 2_0/analysis/task1_groups_and_users.csv", stringsAsFactors = F) %>% 
  addTaskCVK2() %>% 
  subset(select = -X)

groups_and_users_t2 <- read.csv2("/home/doberstein/Dropbox/D/uni/IKARion/CVK 2_0/analysis/task2_groups_and_users.csv", stringsAsFactors = F) %>% 
  addTaskCVK2() %>% 
  subset(select = -X)

groups_and_users_t3 <- read.csv2("/home/doberstein/Dropbox/D/uni/IKARion/CVK 2_0/analysis/task3_groups_and_users.csv", stringsAsFactors = F) %>% 
  addTaskCVK2()

groups_and_users_t4 <- read.csv2("/home/doberstein/Dropbox/D/uni/IKARion/CVK 2_0/analysis/task4_groups_and_users.csv", stringsAsFactors = F) %>% 
  addTaskCVK2()

all_groups_and_users <- full_join(groups_and_users_t1, groups_and_users_t2) %>% 
  full_join(groups_and_users_t3) %>% 
  full_join(groups_and_users_t4)

login_data <- merge(x = login_data, y = all_groups_and_users, by = c("user_id", "task"), all.x = T)
#merge <- merge(x = merge, y = all_groups_and_users_t4_6, by = c("user_id", "task"), all.x = T)

login_per_task <- login_data %>% 
  group_by(user_id, task, group_id) %>% 
  summarize(login_count = n()) %>% 
  filter(!is.na(task))


names(all_groups_and_users)

test <- login_data %>% 
  filter(!is.na(group_id))

# 
write.csv2(login_per_task, "/home/doberstein/Dropbox/D/uni/IKARion/CVK 2_0/analysis/CVK_WS_19_20_login_per_task.csv", row.names = F)
write.csv2(login_data, "/home/doberstein/Dropbox/D/uni/IKARion/CVK 2_0/analysis/CVK_WS_19_20_login_dataset.csv", row.names = F)

```



```{r}
one <- login_data[51,]
```

























*** old stuff

```{r}
library(dplyr)
library(jsonlite)
library(magrittr)
```
user activity endpoint
http://ikarion.collide.info:5000/user_model/user_actions/<course_id>/<user_id>/<verb>

```{r}
getData <- function(...) {
  
  paste("http://ikarion.collide.info:5000", ..., sep="/") %>%
    URLencode %>%
    #print() %>% 
    fromJSON %>%
    extract2("data")
}

replaceUrlChars <- function(string) {
  string <- gsub("/", "$slash$", string)
  string <- gsub("?", "$qmark$", string, fixed = T)
}

all_data <- data_frame()
first_dataset <- data_frame()

getUserActivities <- function(course_id, user_id, verb) {
  #browser()
  #data <- as.data.frame(getData("user_model/user_actions", course_id, user_id, verb))
  #browser()
  
  data <- getData("user_model/user_actions", course_id, replaceUrlChars(user_id), verb)
  #if (nrow(data) > 0) {
  if (length(data) > 0) {
  #if (!dim(data)[1] == 0) {
    data <- data %>% subset(select = -object_name)
    
    all_data <<- rbind(all_data, data)
  }
  
    
  
  #rownames(data) <- NULL
  #rownames(all_data) <- NULL
  #browser()
  #
  #first_dataset <<- data
  #print(data)
  #print(all_data)
  #all_data <<- rbind(all_data, data)
  
  #browser()
  
}



```


getting user list for cvk course
```{r}
#http://ikarion.collide.info:5000/user_model/https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=11

course_id <- "https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=11"
login <- "https://brindlewaye.com/xAPITerms/verbs/loggedin/" %>% replaceUrlChars()
view <- "http://id.tincanapi.com/verb/viewed" %>% replaceUrlChars()

verb <- login

for (user in users$user_id) {
  getUserActivities(course_id, user, verb)
}

users <- getData("user_model") %>% 
  as_data_frame %>% 
  rename(user_id = value)

%>% 
  rowwise() %>% 
  do(getUserActivities(course_id, replaceUrlChars(.$user_id), verb))# %>% ungroup()




%>% 
  rowwise() %>% 
  do(getUserActivities(course_id, replaceUrlChars(.$user_id), verb)) %>% ungroup()



#%>% 
#    distinct(courseid, .keep_all = TRUE)
```

```{r}
first_user <- users[1,]$user_id %>% replaceUrlChars()
login <- "https://brindlewaye.com/xAPITerms/verbs/loggedin/" %>% replaceUrlChars()
view <- "http://id.tincanapi.com/verb/viewed" %>% replaceUrlChars()

# logins
# http://ikarion.collide.info:5000/user_model/user_actions/https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=11/nlrrOSj7CO4Pk21IIcDnog==/https:$slash$$slash$brindlewaye.com$slash$xAPITerms$slash$verbs$slash$loggedin$slash$
  
# views
http://ikarion.collide.info:5000/user_model/user_actions/https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=11/nlrrOSj7CO4Pk21IIcDnog==/http:$slash$$slash$id.tincanapi.com$slash$verb$slash$viewed
  
  
```


```{r}
data1 <- getData("user_model/user_actions/https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=11/nlrrOSj7CO4Pk21IIcDnog==/https:$slash$$slash$brindlewaye.com$slash$xAPITerms$slash$verbs$slash$loggedin$slash$") 

data1 <- getData("user_model/user_actions/https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=11", replaceUrlChars(users[1,]$user_id), "https:$slash$$slash$brindlewaye.com$slash$xAPITerms$slash$verbs$slash$loggedin$slash$") %>% 
  subset(select = -object_name)

data2 <- getData("user_model/user_actions/https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=11", replaceUrlChars(users[2,]$user_id), "https:$slash$$slash$brindlewaye.com$slash$xAPITerms$slash$verbs$slash$loggedin$slash$") %>% 
  subset(select = -object_name)

emp_data <- getData("user_model/user_actions/https:$slash$$slash$moodle.ikarion-projekt.de$slash$course$slash$view.php$qmark$id=11/EA12iYsCduiMrz+xSdFQjQ==/https:$slash$$slash$brindlewaye.com$slash$xAPITerms$slash$verbs$slash$loggedin$slash$")

all_data <- bind_rows(data1, data2)

data1[1,]$

%>% 
  as_data_frame
```
